/* Original activities grounded in the supplied G9 reference, Lesson 1. */
window.REACTION_GAMES = [
{id:'combination',group:'01 · Direct combination',title:'Build a Compound',description:'Combine reactants, assemble products, and identify metal oxides.',pattern:'A + B → AB',tasks:[
{kind:'build',prompt:'Magnesium combines with oxygen. Build the balanced equation in order.',bank:['2Mg','+','O₂','→','2MgO','MgCl₂'],answer:['2Mg','+','O₂','→','2MgO'],explain:'Two magnesium atoms combine with one oxygen molecule to form magnesium oxide.',hint:'There is one product. Count the oxygen atoms on both sides.'},
{kind:'choose',prompt:'Select the observation that matches burning magnesium in air.',equation:'2Mg + O₂ → 2MgO',options:['Bright white light and a white solid','A black solid with no visible flame','A blue solution','A gas that turns limewater turbid'],answer:0,explain:'Magnesium burns with bright white light and forms white magnesium oxide.',hint:'The product is magnesium oxide.'},
{kind:'choose',prompt:'Copper wire is heated in air. Which product appears?',options:['CuO · black copper(II) oxide','CuCl₂ · copper chloride','Cu · red copper','CO₂ · carbon dioxide'],answer:0,explain:'Heated copper forms a black layer of copper(II) oxide: 2Cu + O₂ → 2CuO.',hint:'The metal reacts with oxygen from air.'},
{kind:'build',prompt:'Build the equation for the main oxide formed when steel wool burns in air.',bank:['3Fe','2O₂','Fe₃O₄','Fe₂O₃','+','→'],answer:['3Fe','+','2O₂','→','Fe₃O₄'],explain:'Burning steel wool mainly produces magnetic iron oxide, Fe₃O₄, with bright sparks.',hint:'Use the product containing three iron atoms and four oxygen atoms.'}]},
{id:'decomposition',group:'02 · Decomposition',title:'Break the Compound',description:'Use heat to predict products of oxides and carbonates.',pattern:'AB → A + B',tasks:[
{kind:'build',prompt:'Arrange the thermal decomposition equation for mercury(II) oxide.',bank:['2HgO','→','2Hg','+','O₂','H₂'],answer:['2HgO','→','2Hg','+','O₂'],explain:'On heating, mercury(II) oxide decomposes into mercury and oxygen. Heat is a reaction condition.',hint:'The oxide releases its oxygen; it does not produce hydrogen.'},
{kind:'choose',prompt:'Which observations match this virtual decomposition?',equation:'2HgO —heat→ 2Hg + O₂',options:['Silver-coloured mercury and a gas that relights a glowing splint','A blue solution and carbon dioxide','A white precipitate and hydrogen','A black oxide only'],answer:0,explain:'Mercury is silver-coloured. Oxygen supports combustion and relights a glowing splint.',hint:'Identify the metal and the gas shown in the equation.'},
{kind:'build',prompt:'Heat calcium carbonate. Build its decomposition equation.',bank:['CaCO₃','CaO','CO₂','O₂','+','→'],answer:['CaCO₃','→','CaO','+','CO₂'],explain:'Calcium carbonate decomposes into calcium oxide and carbon dioxide.',hint:'A metal carbonate gives a metal oxide and carbon dioxide.'},
{kind:'choose',prompt:'The gas from heated calcium carbonate passes into clear limewater briefly. Predict the result.',options:['Limewater turns turbid','Limewater turns blue','The gas burns with a pop','Mercury forms'],answer:0,explain:'Carbon dioxide turns clear limewater turbid by forming calcium carbonate.',hint:'This is the test for carbon dioxide.'}]},
{id:'single-acid',group:'03 · Single replacement / Acid',title:'Beat Hydrogen',description:'Use the reactivity series to predict metal–acid reactions.',pattern:'Metal + dilute acid → salt + H₂',tasks:[
{kind:'order',prompt:'Rank these metals from most reactive to least reactive.',bank:['Cu','Fe','Mg','Zn'],answer:['Mg','Zn','Fe','Cu'],explain:'For these metals the order is Mg > Zn > Fe > Cu. Magnesium, zinc and iron precede hydrogen; copper follows it.',hint:'Magnesium reacts faster than zinc, and zinc faster than iron.'},
{kind:'choose',prompt:'Choose the metal that does not replace hydrogen in dilute hydrochloric acid.',options:['Copper','Magnesium','Zinc','Iron'],answer:0,explain:'Copper is below hydrogen in the reactivity series and does not react with dilute HCl.',hint:'A metal must precede hydrogen to replace it in dilute acid.'},
{kind:'build',prompt:'Build the equation for zinc with dilute hydrochloric acid.',bank:['Zn','2HCl','ZnCl₂','H₂','+','→','Cu'],answer:['Zn','+','2HCl','→','ZnCl₂','+','H₂'],explain:'Zinc replaces hydrogen in the acid, producing zinc chloride and hydrogen.',hint:'The salt contains zinc and chloride. Two hydrogen atoms make H₂.'},
{kind:'choose',prompt:'Which observation identifies the evolved hydrogen in a virtual test?',options:['It burns with a pop','It turns limewater turbid','It relights a glowing splint','It makes a blue solution'],answer:0,explain:'Hydrogen burns with a pop. Carbon dioxide turns limewater turbid; oxygen relights a glowing splint.',hint:'Compare the three standard gas tests.'}]},
{id:'single-water',group:'04 · Single replacement / Water',title:'Water Reaction Lab',description:'Compare sodium and magnesium in cold and hot water.',pattern:'Reactive metal + water → hydroxide + H₂',tasks:[
{kind:'choose',prompt:'In this virtual lab, sodium is added to cold water. Predict the products.',options:['Sodium hydroxide and hydrogen','Sodium chloride and oxygen','Sodium oxide and carbon dioxide','No reaction'],answer:0,explain:'Sodium replaces hydrogen in water, forming sodium hydroxide and hydrogen.',hint:'The solution becomes alkaline.'},
{kind:'build',prompt:'Build the balanced sodium–water equation.',bank:['2Na','2H₂O','2NaOH','H₂','O₂','+','→'],answer:['2Na','+','2H₂O','→','2NaOH','+','H₂'],explain:'2Na + 2H₂O → 2NaOH + H₂. The reaction also releases heat.',hint:'Two sodium atoms require two hydroxide groups.'},
{kind:'choose',prompt:'Choose the correct magnesium observation from the lesson.',options:['Bubbles in hot water; no noticeable reaction in cold water','Instant vigorous reaction in cold water like sodium','Copper deposits on magnesium in pure water','A white silver chloride precipitate forms'],answer:0,explain:'The lesson compares magnesium in cold and hot water: hydrogen bubbles are observed in hot water, while none are seen in cold water.',hint:'Magnesium is less reactive than sodium.'},
{kind:'choose',prompt:'Sodium reacts in the virtual tank. Why does it float on water?',options:['Its density is lower than water','Its density is higher than water','It is an insoluble salt','It contains copper ions'],answer:0,explain:'Sodium floats because its density is lower than water. The reaction can be vigorous and release heat.',hint:'Floating depends on relative density.'}]},
{id:'single-salt',group:'05 · Single replacement / Salt solution',title:'Metal Swap',description:'Predict metal displacement and changes in solution colour.',pattern:'A + BC → AC + B',tasks:[
{kind:'choose',prompt:'Zinc is placed in blue copper sulphate solution. Choose the expected observation.',options:['Blue colour fades and red copper deposits','Blue colour becomes darker with no deposit','Hydrogen burns with a pop','A white silver chloride precipitate forms'],answer:0,explain:'Zinc replaces copper, producing colourless zinc sulphate solution and red copper.',hint:'Zinc is more reactive than copper.'},
{kind:'build',prompt:'Build the zinc–copper sulphate equation.',bank:['Zn','CuSO₄','ZnSO₄','Cu','ZnCl₂','+','→'],answer:['Zn','+','CuSO₄','→','ZnSO₄','+','Cu'],explain:'Zinc displaces copper from its salt solution.',hint:'The sulphate group stays together.'},
{kind:'choose',prompt:'Copper is placed in zinc sulphate solution. What happens?',options:['No displacement occurs','Zinc deposits on the copper','Hydrogen is evolved','Silver chloride forms'],answer:0,explain:'Copper is less reactive than zinc and cannot replace it from its salt solution.',hint:'Replacement only works when the added metal is more reactive.'},
{kind:'choose',prompt:'Which metal can replace copper from copper sulphate solution?',options:['Iron','Silver','Gold','Copper'],answer:0,explain:'Iron precedes copper in the reactivity series: Fe + CuSO₄ → FeSO₄ + Cu.',hint:'Choose a metal above copper in the reactivity series.'}]},
{id:'double-alkali',group:'06 · Double replacement / Neutralization',title:'Find Neutral',description:'Make salt and water, then interpret indicator colours.',pattern:'Acid + alkali → salt + water',tasks:[
{kind:'build',prompt:'Neutralize hydrochloric acid with sodium hydroxide. Assemble the equation.',bank:['HCl','NaOH','NaCl','H₂O','H₂','+','→'],answer:['HCl','+','NaOH','→','NaCl','+','H₂O'],explain:'Hydrochloric acid and sodium hydroxide form sodium chloride and water. This is neutralization.',hint:'Neutralization forms water, not hydrogen gas.'},
{kind:'choose',prompt:'Enough acid is added to just neutralize the alkali. What colour is the universal indicator?',options:['Green','Red','Violet','Blue'],answer:0,explain:'Universal indicator is green in a neutral solution.',hint:'Think of the middle of the pH scale.'},
{kind:'choose',prompt:'Excess dilute hydrochloric acid is added after neutralization. Predict the indicator colour.',options:['Red','Green','Violet','White'],answer:0,explain:'Excess strong acid makes the solution acidic; universal indicator turns red.',hint:'The final solution now contains excess acid.'},
{kind:'choose',prompt:'Which salt forms when sulphuric acid neutralizes sodium hydroxide?',options:['Sodium sulphate','Sodium chloride','Calcium carbonate','Silver nitrate'],answer:0,explain:'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. The sulphate comes from sulphuric acid.',hint:'Match the salt anion to the acid.'}]},
{id:'double-acid-salt',group:'07 · Double replacement / Acid and salt',title:'Catch the Gas',description:'React an acid with a carbonate and identify the evolved gas.',pattern:'Acid + carbonate → salt + water + CO₂',tasks:[
{kind:'choose',prompt:'Dilute HCl is added to sodium carbonate. Identify the evolved gas.',options:['Carbon dioxide','Hydrogen','Oxygen','Nitrogen'],answer:0,explain:'The reaction produces carbon dioxide, sodium chloride and water.',hint:'Carbonates release carbon dioxide when they react with acids.'},
{kind:'build',prompt:'Build the overall balanced acid–carbonate equation.',bank:['Na₂CO₃','2HCl','2NaCl','H₂O','CO₂','O₂','+','→'],answer:['Na₂CO₃','+','2HCl','→','2NaCl','+','H₂O','+','CO₂'],explain:'Carbonic acid first forms, then decomposes into water and carbon dioxide. This is the overall equation.',hint:'Use all three products: a chloride salt, water and carbon dioxide.'},
{kind:'choose',prompt:'Choose the gas test that confirms your prediction.',options:['Pass the gas into limewater briefly; it turns turbid','Use a glowing splint; it relights','The gas burns with a pop','Universal indicator becomes violet'],answer:0,explain:'Carbon dioxide produces turbidity in limewater due to calcium carbonate formation.',hint:'Use the carbonate gas test.'},
{kind:'choose',prompt:'Which temporary product breaks down into water and carbon dioxide?',options:['Carbonic acid · H₂CO₃','Hydrochloric acid · HCl','Sodium chloride · NaCl','Sodium hydroxide · NaOH'],answer:0,explain:'H₂CO₃ → H₂O + CO₂ explains the gas evolution after the ion exchange.',hint:'It contains hydrogen, carbon and oxygen.'}]},
{id:'double-precipitation',group:'08 · Double replacement / Precipitation',title:'Spot the Solid',description:'Exchange ions and identify an insoluble precipitate.',pattern:'AB + CD → AD + CB',tasks:[
{kind:'choose',prompt:'Silver nitrate solution is mixed with sodium chloride solution. Predict the visible change.',options:['A white precipitate forms','Red copper deposits','A gas burns with a pop','A bright white flame appears'],answer:0,explain:'Insoluble silver chloride forms as a white precipitate.',hint:'Silver ions combine with chloride ions.'},
{kind:'build',prompt:'Build the precipitation equation.',bank:['AgNO₃','NaCl','AgCl','NaNO₃','Ag','+','→'],answer:['AgNO₃','+','NaCl','→','AgCl','+','NaNO₃'],explain:'AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq). The ions exchange partners.',hint:'Silver takes chloride; sodium takes nitrate.'},
{kind:'choose',prompt:'Which product is the insoluble solid?',options:['AgCl','NaNO₃','AgNO₃','NaCl'],answer:0,explain:'Silver chloride, AgCl, is insoluble in water. The other listed salts dissolve.',hint:'It is the white precipitate in the equation.'},
{kind:'choose',prompt:'What happens to silver chloride after exposure to light for some time?',options:['It turns violet','It becomes a blue solution','It produces hydrogen','It becomes sodium chloride'],answer:0,explain:'The lesson describes white silver chloride turning violet after exposure to light.',hint:'Follow the change in the precipitate colour.'}]},
{id:'redox',group:'09 · Oxidation and reduction',title:'Electron Exchange',description:'Transfer electrons and identify oxidizing and reducing agents.',pattern:'Oxidation: lose e⁻ · Reduction: gain e⁻',tasks:[
{kind:'transfer',prompt:'Zinc reacts with Cu²⁺ ions. Choose the direction of electron transfer.',left:'Zn',right:'Cu²⁺',options:['Zn gives 2e⁻ to Cu²⁺','Cu²⁺ gives 2e⁻ to Zn'],answer:0,explain:'Zn → Zn²⁺ + 2e⁻; Cu²⁺ + 2e⁻ → Cu. Zinc loses electrons and copper ions gain them.',hint:'A neutral zinc atom becomes a positive zinc ion.'},
{kind:'choose',prompt:'Select the oxidation half-reaction.',options:['Mg → Mg²⁺ + 2e⁻','Cu²⁺ + 2e⁻ → Cu','Br₂ + 2e⁻ → 2Br⁻','Ag⁺ + e⁻ → Ag'],answer:0,explain:'Oxidation is loss of electrons. The electrons appear on the product side.',hint:'Use OIL: Oxidation Is Loss.'},
{kind:'choose',prompt:'In Zn + Cu²⁺ → Zn²⁺ + Cu, identify the oxidizing agent.',options:['Cu²⁺','Zn','Zn²⁺','Cu'],answer:0,explain:'Cu²⁺ accepts electrons and is reduced. An oxidizing agent causes the other substance to lose electrons.',hint:'The oxidizing agent is itself reduced.'},
{kind:'choose',prompt:'Hydrogen converts copper(II) oxide to copper: H₂ + CuO → H₂O + Cu. Identify the reducing agent.',options:['H₂','CuO','H₂O','Cu'],answer:0,explain:'Hydrogen removes oxygen from CuO and is itself oxidized to water. H₂ is the reducing agent; CuO is the oxidizing agent.',hint:'The reducing agent is itself oxidized.'}]}
];
