/* Original games grounded in Lesson 2, PDF pages 56–73. */
const C=(prompt,options,answer,explain,hint,scene)=>({kind:'choose',prompt,options,answer,explain,hint:hint||explain,scene});
const B=(prompt,bank,answer,explain)=>({kind:'build',prompt,bank,answer,explain,hint:'Count atoms and keep the reactants on the left.'});
const O=(prompt,bank,answer,explain)=>({kind:'order',prompt,bank,answer,explain,hint:'Think about the cause first, then its effect.'});
const M=(prompt,pairs,explain,scene)=>({kind:'match',prompt,pairs,explain,hint:'Select a card on the left, then its partner on the right.',scene});
const S=(prompt,items,categories,explain,scene)=>({kind:'sort',prompt,items,categories,explain,hint:'Select an item, then choose its correct category.',scene});
window.COMBUSTION_TOPICS=[
{id:'fire',title:'1 · What makes a fire?',description:'Fuel, oxygen, heat and ignition point.',scene:0,games:[
{id:'fire-triangle',title:'Build the Fire Triangle',description:'Match the ingredients and solve a virtual fire puzzle.',tasks:[M('Match each element of the fire triangle to its role.',[['Fuel','Material that burns'],['Oxygen','Supports combustion'],['Heat energy','Reaches ignition point']],'Combustion needs fuel, oxygen and sufficient heat together.',0),S('Sort these cards: a fire-triangle element or not?', [['Fuel',0],['Oxygen',0],['Heat energy',0],['Carbon dioxide',1]],['Triangle element','Not an element'],'Carbon dioxide is not one of the three fire-triangle elements.'),C('A flame is covered so that fresh oxygen cannot reach it. What happens?', ['It continues forever','It goes out when oxygen becomes insufficient','It turns into water','It makes more oxygen'],1,'Removing an element of the fire triangle stops combustion.'),C('Choose the correct definition of combustion.',['A substance reacts with oxygen and releases heat, often light','Any change of physical state','Only a reaction between two metals','Any reaction that absorbs heat'],0,'Combustion forms new substances and releases energy.')]},
{id:'ignition-detective',title:'Ignition Detective',description:'Compare pictures and order the ignition chain.',tasks:[C('Which paper strip reaches ignition point sooner in the pictured comparison?',['Paper wetted with water','Dry paper','Both must ignite at the same time','Neither can absorb heat'],1,'Water absorbs heat and delays the wet strip reaching its ignition point.',null,0),C('Material X has ignition point 45°C; Y has 300°C. Under comparable heating, which ignites more easily?',['Y','X','Both equally','The lower point prevents ignition'],1,'A lower ignition point means less heating is needed to start combustion.'),O('Arrange the simplified match-lighting sequence.',['Match head burns','Friction produces heat','Red phosphorus ignites'],['Friction produces heat','Red phosphorus ignites','Match head burns'],'Friction heats red phosphorus; its ignition initiates reactions that ignite the match head.'),M('Pair each term with its meaning.',[['Ignition point','Lowest temperature needed to start burning'],['Flammability','How easily a material catches fire'],['Combustion','Reaction with oxygen releasing heat']],'Flammability and ignition point describe different properties.')]}
]},
{id:'oxides',title:'2 · Metals and non-metals',description:'Predict oxides and interpret litmus colours.',scene:2,games:[
{id:'oxide-builder',title:'Oxide Workshop',description:'Assemble equations and identify combustion products.',tasks:[B('Build the magnesium combustion equation.',['2Mg','O₂','2MgO','CO₂','+','→'],['2Mg','+','O₂','→','2MgO'],'Magnesium reacts with oxygen to produce white magnesium oxide.'),C('Choose the observation for burning magnesium.',['White ash and bright white light','Blue copper sulphate solution','Black soot only','A gas that burns with a pop'],0,'Burning magnesium forms white MgO and emits bright white light.',null,2),B('Build the complete combustion equation for carbon.',['C','O₂','CO₂','H₂','+','→'],['C','+','O₂','→','CO₂'],'Carbon combines with oxygen to produce carbon dioxide.'),S('Classify the lesson examples of oxides.',[['MgO',0],['CaO',0],['CO₂',1],['SO₂',1]],['Basic oxide','Acidic oxide'],'The lesson contrasts basic metal oxides with acidic non-metal oxides.')]},
{id:'litmus-lab',title:'Colour Clue Lab',description:'Match colour changes to oxide solutions.',tasks:[M('Match the observation to its explanation.',[['Litmus turns blue','Alkaline solution'],['Litmus turns red','Acidic solution'],['Magnesium oxide + water','Magnesium hydroxide forms']],'MgO reacts with water to form an alkaline solution; carbon dioxide in water forms an acidic solution.'),C('CO₂ dissolves in water. Which acid forms?',['Hydrochloric acid','Carbonic acid','Sulphuric acid','Nitric acid'],1,'CO₂ + H₂O forms carbonic acid, H₂CO₃.'),B('Build the magnesium oxide–water equation.',['MgO','H₂O','Mg(OH)₂','CO₂','+','→'],['MgO','+','H₂O','→','Mg(OH)₂'],'Magnesium hydroxide gives alkaline behaviour.'),C('Select the careful scientific statement.',['Every metal oxide dissolves in water','Some basic oxides dissolve or react with water to give alkaline solutions','All non-metal oxides produce alkaline solutions','Litmus blue always means acid'],1,'The lesson specifies that some basic oxides give alkaline solutions in water.')]}
]},
{id:'oxygen',title:'3 · Complete or incomplete?',description:'Control oxygen and investigate flame colour and soot.',scene:1,games:[
{id:'oxygen-control',title:'Oxygen Control Room',description:'Change the air opening and predict the flame.',tasks:[{kind:'burner',prompt:'Adjust the virtual air opening to obtain complete combustion.',answer:'abundant',explain:'Abundant oxygen gives a blue flame and complete combustion. No soot is formed.',hint:'Open the air inlet fully.',scene:1}, {kind:'hotspot',prompt:'Tap the burner showing incomplete combustion.',options:['Left · blue flame','Right · yellow flame'],answer:1,explain:'The yellow flame on the right has limited oxygen and forms soot.',hint:'Look for the yellow flame and black deposit.',scene:1},M('Match each clue to its meaning.',[['Blue flame','Abundant oxygen'],['Yellow or orange flame','Insufficient oxygen'],['Soot','Unburned carbon particles']],'Flame colour and soot provide clues about combustion conditions.',1),C('For equal amounts of the same fuel, which releases more heat?',['Complete combustion','Incomplete combustion','Both always release equal heat','Neither releases heat'],0,'Complete combustion releases more heat than incomplete combustion of the same amount of the same fuel.')]},
{id:'methane-builder',title:'Methane Molecule Mission',description:'Build three combustion equations and compare oxygen needs.',tasks:[B('Assemble complete combustion of methane.',['CH₄','2O₂','CO₂','2H₂O','CO','+','→'],['CH₄','+','2O₂','→','CO₂','+','2H₂O'],'One methane molecule requires two oxygen molecules for complete combustion.'),B('Assemble incomplete combustion forming carbon monoxide.',['2CH₄','3O₂','2CO','4H₂O','CO₂','+','→'],['2CH₄','+','3O₂','→','2CO','+','4H₂O'],'With insufficient oxygen, this pathway forms carbon monoxide and water.'),B('Assemble incomplete combustion forming soot.',['CH₄','O₂','C','2H₂O','CO','+','→'],['CH₄','+','O₂','→','C','+','2H₂O'],'This incomplete-combustion pathway forms solid carbon (soot) and water.'),M('For 2 methane molecules, match the pathway to the number of oxygen molecules.',[['Complete combustion','4 O₂'],['Forms CO and water','3 O₂'],['Forms soot and water','2 O₂']],'The oxygen supply changes the products. Incomplete combustion can form CO or soot, depending on conditions.')]}
]},
{id:'products',title:'4 · Detect combustion products',description:'Use test clues and match product properties.',scene:1,games:[
{id:'gas-detective',title:'Product Detective',description:'Identify gases from evidence and rebuild the test sequence.',tasks:[M('Match the test to the product detected.',[['Clear limewater becomes turbid','Carbon dioxide'],['Anhydrous cobalt chloride: blue → pink','Water'],['Black deposit on a surface','Soot']],'Complete hydrocarbon combustion produces carbon dioxide and water; soot indicates incomplete combustion.'),O('Arrange the water-detection sequence.',['Water is detected','Water vapour condenses on cooling','Blue cobalt chloride paper becomes pink'],['Water vapour condenses on cooling','Blue cobalt chloride paper becomes pink','Water is detected'],'Cooling condenses water vapour; anhydrous cobalt chloride indicates the water.'),C('Which observation confirms CO₂ in the collected products?',['Limewater turns turbid','The gas burns with a pop','Litmus turns blue','White MgO powder appears'],0,'Carbon dioxide reacts with limewater and produces turbidity.'),C('What are the two main products of complete hydrocarbon combustion?',['CO₂ and H₂O','CO and H₂','Soot and oxygen','Nitrogen and magnesium oxide'],0,'Complete combustion of hydrocarbons forms carbon dioxide and water.')]},
{id:'emission-sorter',title:'Emission Card Sorter',description:'Sort pollutants and link each to a distinctive property.',tasks:[S('Sort each substance by its physical form in these lesson examples.',[['Carbon dioxide',0],['Carbon monoxide',0],['Sulphur dioxide',0],['Soot',1]],['Gas','Solid particles'],'Soot consists of fine black carbon particles; CO₂, CO and SO₂ are gases.'),M('Match each substance to the property that identifies it.',[['CO','Toxic, colourless and odourless'],['SO₂','Choking odour; forms sulphurous acid in water'],['NO₂','Reddish-brown gas'],['CO₂','Neither burns nor supports combustion']],'Combustion products have different properties and environmental effects.'),C('Sulphur impurities in a fuel burn. Which gas and acid match the lesson?',['SO₂ and H₂SO₃','CO and HCl','CO₂ and HNO₃','NO₂ and NaOH'],0,'Sulphur dioxide dissolves in water to form sulphurous acid, H₂SO₃.'),C('A colourless, odourless gas is produced by incomplete hydrocarbon combustion. Which is the toxic product?',['CO','CO₂','O₂','H₂O'],0,'Carbon monoxide is toxic and may be produced by incomplete combustion.')]}
]},
{id:'environment',title:'5 · Pollution investigations',description:'Investigate straw burning, traffic and industrial fuel.',scene:3,games:[
{id:'black-cloud',title:'Black Cloud Investigation',description:'Read the picture, connect causes and trace consequences.',tasks:[C('Which activity in this scene contributes to the black cloud?',['Burning accumulated rice straw','Planting trees','Using solar panels','Collecting straw without burning'],0,'Burning agricultural waste releases harmful gases and suspended soot particles.',null,3),O('Arrange this cause-and-effect chain.',['Dark smoke and pollutants are released','Accumulated straw limits oxygen reaching inner parts','Incomplete combustion occurs'],['Accumulated straw limits oxygen reaching inner parts','Incomplete combustion occurs','Dark smoke and pollutants are released'],'Accumulated rice straw can prevent an adequate oxygen supply, promoting incomplete combustion.'),S('Sort these outcomes of the black cloud.',[['Reduced visibility',0],['Difficulty breathing',0],['More asthma and chest allergy cases',0],['Cleaner air',1]],['Harmful outcome','Not an outcome'],'The lesson links the black cloud to reduced visibility and respiratory difficulties.'),M('Match each source to its context.',[['Rice-straw burning','Agricultural waste'],['Fuel burned inside vehicles','Car engines'],['Coal burned for thermal energy','Industry']],'Agriculture, vehicles and industry can all contribute combustion emissions.')]},
{id:'city-investigator',title:'City Air Investigator',description:'Compare sources and identify actions that reduce pollution.',tasks:[C('Which vehicle choice reduces exhaust at the point of use?',['An electric bus','An unmaintained petrol engine','A vehicle with reduced engine efficiency','A vehicle burning more fuel while idling'],0,'The lesson identifies electric vehicles and eco-friendly public transport as pollution-reduction options.',null,4),M('Connect each action with its purpose.',[['Maintain car engines','Improve engine efficiency'],['Use public transport','Reduce individual vehicle use'],['Switch to electric vehicles','Avoid combustion exhaust at the vehicle']],'Engine maintenance and transport choices can reduce pollution from car exhaust.'),C('The lesson prefers natural gas to coal as an industrial thermal-energy fuel. Why?',['It produces fewer carbon particles and sulphur oxides','It produces no CO₂ at all','Coal contains no carbon','Natural gas never undergoes combustion'],0,'Compared with coal, natural gas generally produces less soot and sulphur oxides. It still produces CO₂.',null,5),S('Choose cleaner options from these cards.',[['Solar electricity',0],['Wind electricity',0],['Factory chimney filters',0],['Burning rice straw',1]],['Reduces combustion pollution','Adds pollution'],'Renewable electricity and emission-control equipment help reduce pollution.')]}
]},
{id:'solutions',title:'6 · Clean-air engineering',description:'Catalytic converters, scrubbers and conservation of mass.',scene:5,games:[
{id:'clean-air-engineer',title:'Clean-air Engineer',description:'Pair treatment systems with their jobs and order a scrubber process.',tasks:[M('Match the device or measure to its main role.',[['Catalytic converter','Converts some exhaust pollutants'],['Chimney filter','Captures particles before release'],['Acid-gas scrubber','Treats acidic gases with an alkali']],'Different controls treat different components of emissions.',5),O('Arrange the simplified acid-gas scrubber process.',['Safe salts form and are removed','Acidic gas enters the scrubber','Gas meets an alkaline spray'],['Acidic gas enters the scrubber','Gas meets an alkaline spray','Safe salts form and are removed'],'Acid–alkali neutralization reduces acidic gases released from factory chimneys.',5),C('Which reaction type is used in acid-gas scrubbers?',['Neutralization','Physical melting only','Sublimation','Magnetic separation'],0,'Acidic gases react with an alkaline solution in neutralization reactions.'),C('Why can treating acidic emissions reduce acid rain formation?',['Fewer acidic gases reach the atmosphere','It releases more sulphur dioxide','It turns all gases into oxygen','It prevents every kind of rain'],0,'Reducing acidic emissions reduces their dissolution in rainwater.')]},
{id:'converter-challenge',title:'Exhaust Rescue',description:'Trace conversions and finish with a mass-balance puzzle.',tasks:[M('Match each catalytic-converter example in the lesson.',[['Carbon monoxide (CO)','Converted to carbon dioxide (CO₂)'],['Nitrogen oxides (NOₓ)','Converted to nitrogen (N₂)'],['Catalyst','Speeds up a reaction without being consumed']],'Catalytic converters reduce some toxic exhaust components through chemical reactions.',4),C('Does converting CO to CO₂ remove every environmental concern?',['No: CO₂ remains a combustion emission','Yes: no gas leaves the exhaust','Yes: CO₂ is oxygen','Yes: the carbon disappears'],0,'A converter reduces toxicity of some pollutants; it does not eliminate all emissions.'),C('A closed system contains 16 g methane and 64 g oxygen before complete combustion. What is the total product mass?',['80 g','64 g','16 g','48 g'],0,'Total mass is conserved: 16 + 64 = 80 g. Include all products, including gases.'),O('Arrange the complete-combustion reasoning chain.',['Total mass of products equals total mass of reactants','Methane and oxygen react','Atoms rearrange into CO₂ and H₂O'],['Methane and oxygen react','Atoms rearrange into CO₂ and H₂O','Total mass of products equals total mass of reactants'],'Combustion rearranges atoms; it does not destroy them.')]}
]}
];
window.COMBUSTION_GAMES=window.COMBUSTION_TOPICS.flatMap(t=>t.games.map(g=>({...g,group:t.title,pattern:'Combustion · Environmental pollution',topic:t.id})));
